### PR TITLE
Issue #18 - NPE with Array generator

### PR DESCRIPTION
**Pull request by ymohdriz**
@djodjoni

Hi, 

First of all, thanks for this project. Its really useful for my project. 
I have fixed the NPE when minItems, maxItems is not set in the json schema when the type is 'array'.
Detailed issue description: https://github.com/apptik/JustJson/pull/17

I request you to do the code review and inform me if any changes are required.

Thanks,
Mohammed Rizwan

### CODE REVIEW

**Comment by Malligarjunan** [comment]
@djodjoni - Any idea when this fix can be merged?

**Review by Malligarjunan — COMMENTED** [review]
Code changes looks Good. Could someone merge the changes?

**Comment by djodjoni** [comment]
Hey @Malligarjunan ! Thank you for the input! I will make a new release in the next days !

**Comment by rvenkateshkumar86-cts** [comment]
@djodjoni Latest jar available in maven doesnt have fix for NPE for arraygenerator as per issue #18. can you please share latest jar for NPE with ArrayGenerator

**Pull request merged**
